version: '3.8'

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - web_network
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  web_network:
  db_network:

volumes:
  db_data:
