apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter
        env:
        - name: DATA_SOURCE_NAME
          value: "root:tony-4523@(mysql-server:3306)/"
        ports:
        - containerPort: 9104
