name: Good CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd lab4
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: test
        run: |
          cd lab4
          pytest test.py

      - name: Deploy to production
        if: steps.test.outcome == 'success'
        run: |
          echo "Чай все-таки с сахаром"
          
      - name: Skip deployment
        if: steps.test.outcome != 'success'
        run: |
          echo "Тесты завершились с ошщибкой, поэтому чай только со слезами"
